import { useMemo, useState } from 'react';
import { ArrowRight, Check, ChevronDown, FlaskConical, History, Info, Lightbulb, MessageCircleQuestion, RotateCcw, ShieldAlert, SlidersHorizontal } from 'lucide-react';
import { scenarios } from '../data';
import { useMarketData } from '../market/MarketDataContext';
import { type TwinImpact, type TwinResponse, productApi } from '../product/api';
import { ActionButton, FieldLabel, Hairline, MicroLabel, SegButton, VerdictPill } from '../components/ui';

type Nav = (view: string, payload?: unknown) => void;
const ASSET_NAMES: Record<string, string> = { rNVDA: 'Nvidia', rTSLA: 'Tesla', rAAPL: 'Apple', rMSFT: 'Microsoft', rAMD: 'AMD', rQQQ: 'Nasdaq 100 tracker' };
const DEFAULT_CHALLENGES = ['The size of the market move', 'The time horizon', 'The estimated asset reaction', 'The historical evidence', 'The confidence level', 'The assumption that historical relationships still apply', 'I have company-specific information'];
const assetName = (impact: TwinImpact) => impact.asset_name || ASSET_NAMES[impact.symbol] || impact.symbol;
const confidencePhrase = (value: number) => value < 40 ? 'Limited evidence' : value < 60 ? 'Mixed evidence' : value < 80 ? 'Fairly strong, but not conclusive' : 'Stronger evidence, but not a forecast';
const sensitivityLabel = (value: number) => Math.abs(value) >= 10 ? 'Very high historical sensitivity' : Math.abs(value) >= 6 ? 'High historical sensitivity' : Math.abs(value) >= 3 ? 'Moderate historical sensitivity' : 'Lower historical sensitivity';
const impactColor = (value: number) => value < 0 ? 'text-[#C93A3A]' : 'text-[#0D7A4F]';

function safeSummary(result: TwinResponse) { return result.explanation_view?.plain_summary || `${result.explanation} This is a hypothetical stress test, not a forecast or recommendation.`; }

export default function MarketTwinScreen({ onNav, initialPrompt }: { onNav: Nav; initialPrompt?: string }) {
  const { assets } = useMarketData();
  const [prompt, setPrompt] = useState(initialPrompt || 'What if Nasdaq falls 5% before the U.S. open?');
  const [severity, setSeverity] = useState(62);
  const [duration, setDuration] = useState('24H');
  const [result, setResult] = useState<TwinResponse | null>(null);
  const [alternative, setAlternative] = useState<TwinResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [alternativeLoading, setAlternativeLoading] = useState(false);
  const [error, setError] = useState('');
  const [expandedImpact, setExpandedImpact] = useState<string | null>(null);
  const [expandedHistory, setExpandedHistory] = useState<string | null>(null);
  const [showExplain, setShowExplain] = useState(false);
  const [showChallenge, setShowChallenge] = useState(false);
  const [showAssumptions, setShowAssumptions] = useState(false);
  const [understood, setUnderstood] = useState(false);
  const [selectedChallenge, setSelectedChallenge] = useState('');
  const [customObjection, setCustomObjection] = useState('');
  const [alternativeSeverity, setAlternativeSeverity] = useState(48);
  const [alternativeDuration, setAlternativeDuration] = useState('24H');
  const trackedSymbols = useMemo(() => assets.slice(0, 6).map((asset) => asset.symbol), [assets]);
  const challengeOptions = result?.challenge_options?.length ? result.challenge_options : DEFAULT_CHALLENGES;
  const topImpacts = result ? [...result.impacts].sort((a, b) => Math.abs(b.impact_pct) - Math.abs(a.impact_pct)) : [];

  const run = async () => {
    if (loading) return;
    if (prompt.trim().length < 3) { setError('Describe one market change to simulate. For example: “Nasdaq falls 5%.”'); return; }
    setLoading(true); setError(''); setAlternative(null); setUnderstood(false);
    try { const next = await productApi.simulate({ prompt: prompt.trim(), symbols: trackedSymbols, severity, duration }); setResult(next); setAlternativeSeverity(Math.max(10, severity - 15)); setAlternativeDuration(duration); }
    catch (cause) { setError(cause instanceof Error ? cause.message : 'MarketTwin couldn’t finish this scenario. Please try again.'); }
    finally { setLoading(false); }
  };

  const runAlternative = async (challenge: string, nextSeverity = alternativeSeverity, nextDuration = alternativeDuration) => {
    if (!result || alternativeLoading) return;
    setAlternativeLoading(true); setError('');
    try {
      const next = await productApi.simulate({ prompt: `${result.prompt} Alternative assumption: test ${challenge.toLowerCase()}.`, symbols: trackedSymbols, severity: nextSeverity, duration: nextDuration });
      setAlternative(next);
    } catch (cause) { setError(cause instanceof Error ? cause.message : 'The alternative scenario could not be tested. The original remains unchanged.'); }
    finally { setAlternativeLoading(false); }
  };

  return (
    <div className="fade-up">
      <div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between">
        <div><MicroLabel>MarketTwin · Scenario lab</MicroLabel><h1 className="mt-3 text-[42px] font-semibold tracking-[-0.055em] sm:text-[48px] md:text-[60px]">Change one thing. <span className="serif-italic font-normal text-[#55554F]">See the stress.</span></h1><p className="mt-3 max-w-[720px] text-[15px] leading-6 text-[#55554F]">Ask “what if?” in plain English. MarketTwin estimates how tracked Reality assets could react using live market context and historical calibration. It is a hypothetical stress test, not a forecast.</p></div>
        <FlaskConical className="hidden text-[#D9D7CF] md:block" size={46} strokeWidth={1.2} aria-hidden="true" />
      </div>

      <div className="mt-8 rounded-[28px] border border-[#D9D7CF] bg-white p-5 md:p-8">
        <label className="micro-label text-[#8A8A84]" htmlFor="scenario-prompt">1 · What should change?</label>
        <div className="mt-3 flex items-center gap-3 rounded-2xl border border-[#D9D7CF] bg-[#FAF9F6] px-4 py-3"><FlaskConical size={18} aria-hidden="true" /><input id="scenario-prompt" value={prompt} onChange={(event) => setPrompt(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') void run(); }} className="min-w-0 flex-1 bg-transparent text-[15px] outline-none" /><button type="button" disabled={loading} aria-label="Run scenario from prompt" onClick={() => void run()} className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-[#141412] text-white transition-transform hover:scale-105"><ArrowRight size={15} /></button></div>
        <div aria-live="polite" aria-atomic="true">{error && <p className="mt-3 rounded-xl bg-[#FBEAEA] p-3 text-[13px] leading-5 text-[#A92E3A]">{error}</p>}</div>

        <div className="mt-8 grid gap-7 lg:grid-cols-[1fr_280px]">
          <section id="market-twin-result" className="min-h-[440px] rounded-2xl bg-[#F4F3EF] p-5 md:p-6" aria-busy={loading} aria-label="MarketTwin scenario result">
            {!result && !loading && <div className="flex min-h-[390px] flex-col justify-center"><MicroLabel>3 · Result appears here</MicroLabel><h2 className="mt-4 max-w-[620px] text-[30px] font-semibold tracking-[-0.04em]">Ask “what if?” instead of asking AI to predict the future.</h2><p className="mt-4 max-w-[610px] text-[14px] leading-6 text-[#55554F]">Try a Nasdaq drop, a yield spike, a liquidity shock or another clear event. You will get an understandable summary, estimated ranges, historical context, and a path to challenge the assumptions.</p></div>}
            {loading && <div className="flex min-h-[390px] flex-col justify-center"><MicroLabel>3 · Building the stress test</MicroLabel><h2 className="mt-4 text-[30px] font-semibold tracking-[-0.04em]">Calibrating the shock.</h2><div className="mt-7 space-y-3">{['Understand the scenario', 'Read current market volatility', 'Retrieve historical context', 'Measure benchmark sensitivity', 'Build uncertainty ranges'].map((step) => <div key={step} className="flex items-center gap-3 border-b border-[#DDDCD5] py-3"><span className="shimmer-bar h-2 w-2 rounded-full" /><span className="text-[13px]">{step}</span></div>)}</div></div>}

            {result && !loading && <>
              <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><MicroLabel>3 · {result.shock.category} stress</MicroLabel><h2 className="mt-2 max-w-[630px] text-[25px] font-semibold tracking-[-0.035em]">{result.prompt}</h2><p className="mt-2 text-[12px] text-[#8A8A84]">Scenario: {result.shock.driver} {result.shock.direction} {result.shock.magnitude}{result.shock.unit}</p></div><VerdictPill tone="neutral">{result.duration}</VerdictPill></div>

              <div className="mt-6 rounded-2xl border border-[#141412]/10 bg-white p-5 md:p-6" aria-labelledby="simple-result-heading"><div className="flex items-start justify-between gap-4"><div><MicroLabel className="text-[#1D3DFF]">In simple terms</MicroLabel><h3 id="simple-result-heading" className="mt-2 text-[24px] font-semibold tracking-[-0.035em]">What this scenario means</h3></div><Lightbulb className="text-[#9A6B00]" size={20} aria-hidden="true" /></div><p className="mt-4 text-[15px] leading-7 text-[#2A2A28]">{safeSummary(result)}</p><p className="mt-3 text-[12px] leading-5 text-[#8A8A84]">This is a hypothetical stress test, not a prediction or recommendation. Real results can differ because of news, changing conditions, and company-specific events.</p><div className="mt-5 flex flex-wrap gap-2" role="group" aria-label="Choose what to do with this interpretation"><ActionButton variant={understood ? 'primary' : 'secondary'} onClick={() => setUnderstood(true)}>{understood ? <Check size={14} /> : null} I understand</ActionButton><ActionButton variant="secondary" onClick={() => { setShowChallenge(true); setShowExplain(false); }}>Challenge this</ActionButton><ActionButton variant="secondary" onClick={() => { setShowExplain((value) => !value); setShowChallenge(false); }}>{showExplain ? 'Hide explanation' : 'Why do you think that?'}</ActionButton><ActionButton variant="secondary" onClick={() => { setShowAssumptions((value) => !value); setShowChallenge(false); }}>{showAssumptions ? 'Hide assumptions' : 'Change an assumption'}</ActionButton></div>{understood && <p className="mt-3 text-[12px] text-[#0D7A4F]" role="status">You can still question this result or inspect the evidence below.</p>}</div>

              {showExplain && <div className="mt-4 rounded-2xl border border-[#1D3DFF]/20 bg-[#EEF0FF] p-5" aria-live="polite"><div className="flex items-center gap-2"><Info size={16} className="text-[#1D3DFF]" aria-hidden="true" /><h3 className="text-[14px] font-semibold">Why this estimate looks this way</h3></div><p className="mt-3 text-[13px] leading-6 text-[#2A2A28]">{result.explanation_view?.impact_summary || result.explanation}</p><p className="mt-3 text-[12px] leading-5 text-[#55554F]">Confidence describes the strength and consistency of the available evidence. It is not the probability that an estimated move will happen.</p><ul className="mt-3 space-y-2 text-[12px] leading-5 text-[#55554F]">{(result.explanation_view?.limitations || ['Historical relationships can fail during unusual events.']).map((item) => <li key={item} className="flex gap-2"><span aria-hidden="true">•</span><span>{item}</span></li>)}</ul></div>}

              {showAssumptions && <div className="mt-4 rounded-2xl border border-[#D9D7CF] bg-white p-5" aria-labelledby="assumption-heading"><div className="flex items-center gap-2"><SlidersHorizontal size={16} aria-hidden="true" /><h3 id="assumption-heading" className="text-[14px] font-semibold">Change an assumption</h3></div><p className="mt-2 text-[12px] leading-5 text-[#55554F]">The original scenario stays intact. Test a lower-stress alternative and compare it below.</p><div className="mt-5 grid gap-5 sm:grid-cols-2"><div><FieldLabel>Alternative severity · {alternativeSeverity}/100</FieldLabel><input aria-label="Alternative scenario severity" type="range" min="10" max="100" value={alternativeSeverity} onChange={(event) => setAlternativeSeverity(Number(event.target.value))} className="w-full accent-[#1D3DFF]" /></div><div><FieldLabel>Alternative time horizon</FieldLabel><div className="flex flex-wrap gap-1">{['1H', '6H', '24H', '7D'].map((item) => <SegButton key={item} active={alternativeDuration === item} onClick={() => setAlternativeDuration(item)}>{item}</SegButton>)}</div></div></div><ActionButton disabled={alternativeLoading} onClick={() => void runAlternative('a lower sensitivity assumption')} className="mt-5">{alternativeLoading ? 'Testing…' : 'Test alternative assumption'} <ArrowRight size={14} /></ActionButton></div>}

              {showChallenge && <div className="mt-4 rounded-2xl border border-[#D9D7CF] bg-white p-5" aria-labelledby="challenge-heading"><div className="flex items-center gap-2"><MessageCircleQuestion size={16} aria-hidden="true" /><h3 id="challenge-heading" className="text-[14px] font-semibold">What would you like to challenge?</h3></div><p className="mt-2 text-[12px] leading-5 text-[#55554F]">A challenge tests an assumption; it does not erase the original result.</p><div className="mt-4 grid gap-2 sm:grid-cols-2">{challengeOptions.map((option) => <button type="button" key={option} aria-pressed={selectedChallenge === option} onClick={() => setSelectedChallenge(option)} className={`min-h-11 rounded-xl border px-3 py-2 text-left text-[12px] transition-colors ${selectedChallenge === option ? 'border-[#1D3DFF] bg-[#EEF0FF] text-[#141412]' : 'border-[#E7E5DE] bg-[#FAF9F6] text-[#55554F] hover:border-[#141412]'}`}>{option}</button>)}</div><label htmlFor="custom-objection" className="micro-label mt-5 block text-[#8A8A84]">Optional short objection</label><textarea id="custom-objection" value={customObjection} onChange={(event) => setCustomObjection(event.target.value)} rows={2} maxLength={280} className="mt-2 w-full resize-none rounded-xl border border-[#D9D7CF] bg-[#FAF9F6] p-3 text-[13px] outline-none focus:border-[#1D3DFF]" placeholder="For example: company news may matter more than the index move." />{(selectedChallenge || customObjection.trim()) && <div className="mt-4 rounded-xl bg-[#F4F3EF] p-4"><p className="text-[13px] leading-5 text-[#2A2A28]">That is a reasonable objection. The original estimate assumes historical relationships remain useful and does not include unverified company-specific information.</p><p className="mt-2 text-[12px] leading-5 text-[#55554F]">Test a lower-stress alternative to see how much the interpretation changes.</p><ActionButton disabled={alternativeLoading} onClick={() => void runAlternative(selectedChallenge || 'your written objection')} className="mt-4">{alternativeLoading ? 'Testing…' : 'Test this objection'} <ArrowRight size={14} /></ActionButton></div>}</div>}

              <div className="mt-7"><div className="flex items-center justify-between gap-3"><div><MicroLabel>Most affected assets</MicroLabel><p className="mt-1 text-[12px] text-[#8A8A84]">Start with the plain-English sensitivity label. Open “View why” for the calculation.</p></div><span className="text-[11px] text-[#8A8A84]">{result.impacts.length} tracked</span></div><div className="mt-3 grid gap-3 sm:grid-cols-2">{topImpacts.map((impact) => { const open = expandedImpact === impact.symbol; const panelId = `impact-why-${impact.symbol}`; return <div key={impact.symbol} className="rounded-2xl border border-[#E7E5DE] bg-white p-5"><div className="flex items-start justify-between gap-4"><div><h3 className="font-semibold">{assetName(impact)}</h3><p className="mt-1 text-[11px] text-[#8A8A84]">{impact.symbol}</p></div><span className={`mono-num text-[20px] font-semibold ${impactColor(impact.impact_pct)}`}>{impact.impact_pct > 0 ? '+' : ''}{impact.impact_pct.toFixed(2)}%</span></div><p className="mt-4 text-[12px] font-medium text-[#55554F]">{sensitivityLabel(impact.impact_pct)}</p><p className="mt-2 text-[12px] leading-5 text-[#8A8A84]">Estimated range <span className="mono-num">{impact.lower_pct.toFixed(2)}% to {impact.upper_pct.toFixed(2)}%</span><br />Evidence strength: {confidencePhrase(impact.confidence)}</p><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-[#EDECE7]"><div className={`h-full rounded-full ${impact.impact_pct < 0 ? 'bg-[#C93A3A]' : 'bg-[#0D7A4F]'}`} style={{ width: `${Math.min(96, Math.max(8, Math.abs(impact.impact_pct) * 8))}%` }} /></div><button type="button" aria-expanded={open} aria-controls={panelId} aria-label={`View why ${assetName(impact)} has this estimate`} onClick={() => setExpandedImpact(open ? null : impact.symbol)} className="mt-4 inline-flex min-h-10 items-center gap-2 text-[12px] font-semibold text-[#1D3DFF] hover:text-[#0F22B8]">{open ? 'Hide why' : 'View why'} <ChevronDown size={14} className={open ? 'rotate-180 transition-transform' : 'transition-transform'} /></button>{open && <div id={panelId} className="mt-3 border-t border-[#E7E5DE] pt-3 text-[12px] leading-5 text-[#55554F]"><p>{assetName(impact)} has a measured relationship with the selected benchmark in the available historical data. The estimate applies that relationship to this hypothetical scenario; it does not mean the asset must move this way today.</p><p className="mt-2">Benchmark: Nasdaq 100 / QQQ · frequency: daily where historical data is available · source: {impact.model || 'AlphaArena deterministic stress engine'}.</p>{typeof impact.beta_to_qqq === 'number' && <p className="mt-2">Technical detail: historical sensitivity β {impact.beta_to_qqq.toFixed(2)}. This value is secondary to the plain-English explanation.</p>}<p className="mt-2 text-[#8A8A84]">Company news, changing market conditions, and unusual liquidity can make this estimate wrong.</p></div>}</div>; })}</div></div>

              <div className="mt-6 rounded-2xl border border-[#D9D7CF] bg-white/70 p-5"><div className="flex items-center gap-2"><ShieldAlert size={16} className="text-[#9A6B00]" aria-hidden="true" /><MicroLabel>What could make this estimate wrong?</MicroLabel></div><div className="mt-3 grid gap-2 sm:grid-cols-2">{(result.explanation_view?.limitations || ['Company-specific news', 'A rapid market reversal', 'Historical sensitivity failing during a panic', 'Thin liquidity or unusual trading conditions']).slice(0, 4).map((item) => <div key={item} className="rounded-xl bg-[#F4F3EF] p-3 text-[12px] leading-5 text-[#55554F]">{item}</div>)}</div></div>

              {result.analogues.length > 0 && <div className="mt-6 rounded-2xl border border-[#D9D7CF] bg-white p-5"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><History size={16} aria-hidden="true" /><MicroLabel>Historical context · current move</MicroLabel></div><p className="mt-2 text-[12px] leading-5 text-[#55554F]">{result.historical_context?.selection_disclaimer || 'These daily observations describe the current observed move. They are context, not matches for this hypothetical scenario and not predictions.'}</p></div><span className="text-[11px] text-[#8A8A84]">Daily</span></div><div className="mt-3 divide-y divide-[#DDDCD5]">{result.analogues.slice(0, 3).map((item) => { const key = `${item.label}-${item.outcome}`; const open = expandedHistory === key; return <div key={key} className="py-3"><button type="button" aria-expanded={open} aria-label={`View full historical context for ${item.label}`} onClick={() => setExpandedHistory(open ? null : key)} className="flex min-h-10 w-full items-start justify-between gap-4 text-left"><span><span className="block text-[12px] font-semibold">{item.label}</span><span className="mt-1 block text-[12px] text-[#55554F]">{item.outcome}</span></span><ChevronDown size={14} className={open ? 'mt-1 shrink-0 rotate-180 transition-transform' : 'mt-1 shrink-0 transition-transform'} /></button>{open && <div className="mt-2 rounded-xl bg-[#F4F3EF] p-3 text-[11px] leading-5 text-[#55554F]">Selected mechanically because the underlying’s current observed daily move was similar in direction and size. The next observed daily move is shown for context only; it does not validate this scenario. Source: Vibe-Trading historical market data.</div>}<p className="mt-1 text-[11px] leading-4 text-[#8A8A84]">{item.relevance}</p></div>; })}</div></div>}

              <details className="mt-6 rounded-2xl border border-[#D9D7CF] bg-white"><summary className="flex min-h-12 cursor-pointer list-none items-center justify-between gap-3 px-5 text-[13px] font-semibold"><span>Technical details and data sources</span><ChevronDown size={15} aria-hidden="true" /></summary><div className="border-t border-[#E7E5DE] px-5 py-4 text-[12px] leading-6 text-[#55554F]"><p>How estimated: {result.model_source}. Benchmark move: {result.assumptions?.benchmark_move_pct ?? result.shock.magnitude}% · frequency: {result.historical_context?.data_frequency || 'daily'} · sensitivity method: {result.assumptions?.sensitivity_method || 'historical'}.</p><p className="mt-2">Generated {new Date(result.generated_at).toLocaleString()} · Bitget: {result.sources.market} · Vibe-Trading: {result.sources.vibe} · Signal: {result.sources.signal} · Qwen: {result.sources.qwen}.</p><p className="mt-2 text-[#8A8A84]">Technical terms are secondary: confidence describes evidence strength, not probability, and model source describes text generation rather than measured evidence.</p></div></details>

              {alternative && <div className="mt-6 rounded-2xl border border-[#1D3DFF]/25 bg-[#EEF0FF] p-5" aria-live="polite"><div className="flex items-center justify-between gap-3"><div><MicroLabel className="text-[#1D3DFF]">Alternative assumption</MicroLabel><h3 className="mt-2 text-[18px] font-semibold">The original remains unchanged</h3></div><RotateCcw size={17} className="text-[#1D3DFF]" aria-hidden="true" /></div><p className="mt-3 text-[12px] leading-5 text-[#55554F]">This version tests a changed assumption. It is not a corrected result or a recommendation.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{[topImpacts.slice(0, 3), [...alternative.impacts].sort((a, b) => Math.abs(b.impact_pct) - Math.abs(a.impact_pct)).slice(0, 3)].map((items, index) => <div key={index} className="rounded-xl bg-white p-4"><p className="text-[11px] font-semibold text-[#8A8A84]">{index === 0 ? 'Original historical sensitivity' : 'Alternative assumption'}</p>{items.map((impact) => <div key={impact.symbol} className="mt-2 flex items-center justify-between gap-3 text-[12px]"><span>{assetName(impact)}</span><span className={`mono-num font-semibold ${impactColor(impact.impact_pct)}`}>{impact.impact_pct > 0 ? '+' : ''}{impact.impact_pct.toFixed(2)}%</span></div>)}</div>)}</div></div>}

              <div className="mt-6 flex flex-wrap items-center justify-between gap-3 border-t border-[#DDDCD5] pt-4"><span className="text-[11px] text-[#8A8A84]">Model source: {result.model_source}</span><div className="flex flex-wrap gap-2"><ActionButton variant="secondary" onClick={() => onNav('arena', { symbol: result.impacts[0]?.symbol || 'rNVDA', thesis: result.prompt })}>Use in paper-only Arena <ArrowRight size={14} /></ActionButton><ActionButton variant="ghost" onClick={() => { setResult(null); setAlternative(null); setShowChallenge(false); setShowExplain(false); }}>Run another scenario</ActionButton></div></div>
            </>}
          </section>

          <aside className="rounded-2xl border border-[#E7E5DE] p-5"><div className="flex items-center gap-2"><SlidersHorizontal size={15} aria-hidden="true" /><span className="text-[13px] font-semibold">2 · Tune the stress</span></div><div className="mt-7"><FieldLabel>Severity · {severity}/100</FieldLabel><input aria-label="Scenario severity" type="range" min="10" max="100" value={severity} onChange={(event) => setSeverity(Number(event.target.value))} className="w-full accent-[#141412]" /></div><div className="mt-7"><FieldLabel>Time horizon</FieldLabel><div className="flex flex-wrap gap-1">{['1H', '6H', '24H', '7D'].map((item) => <SegButton key={item} active={duration === item} onClick={() => setDuration(item)}>{item}</SegButton>)}</div></div><Hairline className="my-6" /><FieldLabel>Try an example</FieldLabel><div className="space-y-2">{scenarios.slice(0, 5).map((scenario) => <button type="button" key={scenario.id} onClick={() => { setPrompt(scenario.label); setSeverity(scenario.severity); }} className="flex min-h-11 w-full items-center justify-between gap-3 rounded-xl bg-[#F4F3EF] px-3 py-2.5 text-left text-[12px] hover:bg-[#EDECE7]"><span>{scenario.label}</span><ArrowRight size={12} aria-hidden="true" /></button>)}</div><ActionButton disabled={loading} onClick={() => void run()} className="mt-6 w-full">{loading ? 'Running…' : 'Run scenario'}</ActionButton></aside>
        </div>
      </div>
    </div>
  );
}
